# Generated by Django 5.0.2 on 2024-03-03 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="profile_photo",
            new_name="content",
        ),
    ]
