# Generated by Django 5.0.2 on 2024-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_profile_photo_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
