# Generated by Django 5.0.2 on 2024-03-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_remove_post_comments_post_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
    ]
