# Generated by Django 5.0.2 on 2024-03-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_alter_comment_updated_at"),
        ("posts", "0013_remove_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
        ),
    ]
