# Generated by Django 5.0.2 on 2024-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="<django.db.models.fields.EmailField>",
                max_length=60,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
